# SPDX-FileCopyrightText: Copyright The Zephyr Project Contributors
# SPDX-License-Identifier: Apache-2.0

CONFIG_PRECISION_TIMING=y
CONFIG_PRECISION_CLOCK_OUTPUT=y
CONFIG_PRECISION_TIMING_SHELL=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_PTP_CLOCK_STM32_HAL_OUTPUT=y
CONFIG_ETH_STM32_HAL_PTP_CLOCK_SRC_HZ=100000000
CONFIG_PTP_TIME_RECEIVER_ONLY=y
CONFIG_PTP_IEEE_802_3_PROTOCOL=y
CONFIG_PTP_DELAY_MECHANISM_P2P=y
CONFIG_PTP_NETWORK_MODE_MULTICAST=y
CONFIG_PTP_NETWORK_MODE_HYBRID=n
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_NET_SAMPLE_RUN_DURATION=0
